name = "mercadolimpio-intelligence"
main = "worker_ml.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "ML_KV"
id = "9ec9c5f2335e401e877ebde3c39922b2"
preview_id = "e3ef07f3021c47228da0cb0ccfaed0ef"

[vars]
ADMIN_PIN = "2817"
LAURA_PIN = "laura2024"
PABLO_EMAIL = "	santamariapablodaniel@gmail.com"

# Secrets — cargar con: wrangler secret put GEMINI_API_KEY
# GEMINI_API_KEY  → tu API key de Google AI Studio
# BREVO_API_KEY   → para emails automáticos (opcional)

[[triggers]]
crons = [
  "0 11 * * 1",
  "0 13 1 * *",
  "0 8 * * 1-5"
]
